// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCHGNzV_eBKCG1F4ZFew4IiPl1ums2S48',
    appId: '1:1054179288655:web:4f91991538b5c7d8c8ac3a',
    messagingSenderId: '1054179288655',
    projectId: 'task-management-system-119f9',
    authDomain: 'task-management-system-119f9.firebaseapp.com',
    storageBucket: 'task-management-system-119f9.firebasestorage.app',
    measurementId: 'G-MP861DJJLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChkeH3lIOJBRxvv6ZExiF0gmIe_hnSEns',
    appId: '1:1054179288655:android:661ed562cbfa4383c8ac3a',
    messagingSenderId: '1054179288655',
    projectId: 'task-management-system-119f9',
    storageBucket: 'task-management-system-119f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpA90IkCKk9qZDuF8peMo-WIZJGRrFx_4',
    appId: '1:1054179288655:ios:c89c10c3f24352ddc8ac3a',
    messagingSenderId: '1054179288655',
    projectId: 'task-management-system-119f9',
    storageBucket: 'task-management-system-119f9.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementSystem',
  );
}
